// <auto-generated />
using System;
using Locus.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Locus.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260401180215_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Locus.Models.Chamado", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("DataAbertura")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int?>("EquipamentoId")
                        .HasColumnType("integer");

                    b.Property<int>("SetorId")
                        .HasColumnType("integer");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<int>("TipoServicoId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("EquipamentoId");

                    b.HasIndex("SetorId");

                    b.HasIndex("TipoServicoId");

                    b.ToTable("Chamados");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            DataAbertura = new DateTime(2025, 3, 13, 0, 0, 0, 0, DateTimeKind.Utc),
                            Descricao = "Montagem de computador i3 segunda geração",
                            EquipamentoId = 1,
                            SetorId = 1,
                            Status = 2,
                            TipoServicoId = 3
                        },
                        new
                        {
                            Id = 2,
                            DataAbertura = new DateTime(2025, 3, 13, 0, 0, 0, 0, DateTimeKind.Utc),
                            Descricao = "Instalação do Windows 10 — Notebook Acer Aspire 3, configurar boot",
                            EquipamentoId = 2,
                            SetorId = 1,
                            Status = 2,
                            TipoServicoId = 1
                        },
                        new
                        {
                            Id = 3,
                            DataAbertura = new DateTime(2025, 3, 13, 0, 0, 0, 0, DateTimeKind.Utc),
                            Descricao = "Instalação Office 365 — Notebook",
                            EquipamentoId = 3,
                            SetorId = 1,
                            Status = 2,
                            TipoServicoId = 2
                        },
                        new
                        {
                            Id = 4,
                            DataAbertura = new DateTime(2025, 3, 13, 0, 0, 0, 0, DateTimeKind.Utc),
                            Descricao = "Computador travando, impressora não abre",
                            EquipamentoId = 4,
                            SetorId = 1,
                            Status = 2,
                            TipoServicoId = 3
                        },
                        new
                        {
                            Id = 5,
                            DataAbertura = new DateTime(2025, 3, 13, 0, 0, 0, 0, DateTimeKind.Utc),
                            Descricao = "Ativar Windows",
                            EquipamentoId = 5,
                            SetorId = 1,
                            Status = 2,
                            TipoServicoId = 6
                        },
                        new
                        {
                            Id = 6,
                            DataAbertura = new DateTime(2025, 3, 13, 0, 0, 0, 0, DateTimeKind.Utc),
                            Descricao = "Instalação Office 365 — Desktop",
                            EquipamentoId = 6,
                            SetorId = 3,
                            Status = 2,
                            TipoServicoId = 2
                        },
                        new
                        {
                            Id = 7,
                            DataAbertura = new DateTime(2025, 3, 13, 0, 0, 0, 0, DateTimeKind.Utc),
                            Descricao = "Instalação de Toner",
                            EquipamentoId = 7,
                            SetorId = 3,
                            Status = 2,
                            TipoServicoId = 5
                        },
                        new
                        {
                            Id = 8,
                            DataAbertura = new DateTime(2025, 3, 20, 0, 0, 0, 0, DateTimeKind.Utc),
                            Descricao = "Instalação de SSD — Desktop",
                            EquipamentoId = 8,
                            SetorId = 2,
                            Status = 2,
                            TipoServicoId = 3
                        },
                        new
                        {
                            Id = 9,
                            DataAbertura = new DateTime(2025, 3, 20, 0, 0, 0, 0, DateTimeKind.Utc),
                            Descricao = "Instalação do Windows 10 — Desktop",
                            EquipamentoId = 9,
                            SetorId = 2,
                            Status = 2,
                            TipoServicoId = 1
                        },
                        new
                        {
                            Id = 10,
                            DataAbertura = new DateTime(2025, 3, 20, 0, 0, 0, 0, DateTimeKind.Utc),
                            Descricao = "Instalação de driver de impressora — Desktop",
                            EquipamentoId = 10,
                            SetorId = 2,
                            Status = 2,
                            TipoServicoId = 4
                        },
                        new
                        {
                            Id = 11,
                            DataAbertura = new DateTime(2025, 3, 28, 0, 0, 0, 0, DateTimeKind.Utc),
                            Descricao = "Instalação de driver de impressora — Notebook",
                            EquipamentoId = 11,
                            SetorId = 1,
                            Status = 2,
                            TipoServicoId = 4
                        });
                });

            modelBuilder.Entity("Locus.Models.Equipamento", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Modelo")
                        .HasColumnType("text");

                    b.Property<int>("SetorId")
                        .HasColumnType("integer");

                    b.Property<int>("Tipo")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("SetorId");

                    b.ToTable("Equipamentos");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Modelo = "Montagem i3",
                            SetorId = 1,
                            Tipo = 0
                        },
                        new
                        {
                            Id = 2,
                            Modelo = "Acer Aspire 3",
                            SetorId = 1,
                            Tipo = 1
                        },
                        new
                        {
                            Id = 3,
                            Modelo = "Notebook G1",
                            SetorId = 1,
                            Tipo = 1
                        },
                        new
                        {
                            Id = 4,
                            Modelo = "Desktop S1",
                            SetorId = 1,
                            Tipo = 0
                        },
                        new
                        {
                            Id = 5,
                            Modelo = "Desktop S2",
                            SetorId = 1,
                            Tipo = 0
                        },
                        new
                        {
                            Id = 6,
                            Modelo = "Desktop B1",
                            SetorId = 3,
                            Tipo = 0
                        },
                        new
                        {
                            Id = 7,
                            Modelo = "HP LaserJet",
                            SetorId = 3,
                            Tipo = 2
                        },
                        new
                        {
                            Id = 8,
                            Modelo = "Desktop F1",
                            SetorId = 2,
                            Tipo = 0
                        },
                        new
                        {
                            Id = 9,
                            Modelo = "Desktop F2",
                            SetorId = 2,
                            Tipo = 0
                        },
                        new
                        {
                            Id = 10,
                            Modelo = "Desktop F3",
                            SetorId = 2,
                            Tipo = 0
                        },
                        new
                        {
                            Id = 11,
                            Modelo = "Notebook S3",
                            SetorId = 1,
                            Tipo = 1
                        });
                });

            modelBuilder.Entity("Locus.Models.Setor", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Setores");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Nome = "Secretaria"
                        },
                        new
                        {
                            Id = 2,
                            Nome = "Financeiro"
                        },
                        new
                        {
                            Id = 3,
                            Nome = "Biblioteca"
                        });
                });

            modelBuilder.Entity("Locus.Models.TipoServico", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("TiposServico");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Nome = "Instalação SO"
                        },
                        new
                        {
                            Id = 2,
                            Nome = "Instalação Office"
                        },
                        new
                        {
                            Id = 3,
                            Nome = "Montagem"
                        },
                        new
                        {
                            Id = 4,
                            Nome = "Instalação Driver"
                        },
                        new
                        {
                            Id = 5,
                            Nome = "Instalação Toner"
                        },
                        new
                        {
                            Id = 6,
                            Nome = "Ativação Windows"
                        });
                });

            modelBuilder.Entity("Locus.Models.Chamado", b =>
                {
                    b.HasOne("Locus.Models.Equipamento", "Equipamento")
                        .WithMany("Chamados")
                        .HasForeignKey("EquipamentoId");

                    b.HasOne("Locus.Models.Setor", "Setor")
                        .WithMany("Chamados")
                        .HasForeignKey("SetorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Locus.Models.TipoServico", "TipoServico")
                        .WithMany("Chamados")
                        .HasForeignKey("TipoServicoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Equipamento");

                    b.Navigation("Setor");

                    b.Navigation("TipoServico");
                });

            modelBuilder.Entity("Locus.Models.Equipamento", b =>
                {
                    b.HasOne("Locus.Models.Setor", "Setor")
                        .WithMany("Equipamentos")
                        .HasForeignKey("SetorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Setor");
                });

            modelBuilder.Entity("Locus.Models.Equipamento", b =>
                {
                    b.Navigation("Chamados");
                });

            modelBuilder.Entity("Locus.Models.Setor", b =>
                {
                    b.Navigation("Chamados");

                    b.Navigation("Equipamentos");
                });

            modelBuilder.Entity("Locus.Models.TipoServico", b =>
                {
                    b.Navigation("Chamados");
                });
#pragma warning restore 612, 618
        }
    }
}
